### ISSUE TITLE
404 page does not render toolbar

### ISSUE THREAD

**Issue by kagux** [kagux/ex_debug_toolbar#31]

**Comment by epilgrim** [comment]
404 pages do render, as long as the html is complete:
```
<html>
<head></head>
<body></body>
</html>
```
The thing is that default 404 pages have only text. therefore the Injector does not do it's job
I see 2 possibilities:
1. We read the response type from the conn, and if it's html, we ensure that there is a complete html page
2. We add some kind of parameter, if it's present, we ensure there is a complete html page. This will also allow us to use the toolbar in json apis, for example (of course, breaking the json, but that would be intended if the parameter is there
