### ISSUE TITLE
Allow iex usage?

### ISSUE THREAD

**Issue by sardaukar** [kagux/ex_debug_toolbar#40]
Right now, if I enable `ex_debug_toolbar` (which is awesome, btw, thanks!) I can run it on the server, but if I start an `iex` session, I get:

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

=INFO REPORT==== 18-Aug-2017::14:21:23 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application ex_debug_toolbar: ExDebugToolbar.Application.start(:normal, []) returned an error: shutdown: failed to start child: ExDebugToolbar.Breakpoint.ServerNode
    ** (EXIT) :error
```

The only workaround is disabling the toolbar in `dex.exs` - is there a better way?

Thanks.

**Comment by kagux** [comment]
Hey @sardaukar, thanks for bringing this up. I've published an update addressing this. Could you verify that it fixed the issue?

**Comment by sardaukar** [comment]
it has @kagux ! thanks!
