### ISSUE TITLE
Javascript confirms for delete are shown twice

### ISSUE THREAD

**Issue by sardaukar** [kagux/ex_debug_toolbar#44]
Hello again!

When using this lib in a page with a `data-confirm` message for deletion, like the default Elixir generated scaffold pages, the message is shown twice. 

Is there a way around this? Thanks!

**Comment by kagux** [comment]
Hello @sardaukar,

I've just published update that should fix this issue. Thanks for spotting it!

**Comment by sardaukar** [comment]
Thanks! You're really quick :D
