### ISSUE TITLE
Question: Displaying historical requests (e.g. the post request before a get request)

### ISSUE THREAD

**Issue by roberthopman** [kagux/ex_debug_toolbar#48]
Interested to know how to get the historical requests, e.g. the post/delete request before a get request.

**Comment by kagux** [comment]
Hey @roberthopman,

That's a great question and it has been on our minds recently. Technically, request data is accessible, and we build toolbar with historical data in mind. 

We're debating on how it should be presented. Here're a couple of options:
* separate UI (page/modal/etc) to display a list of requests with associated data (think of symfony)
* a new panel with a list of recent requests (path, method, status, timestamp). clicking each row replaces data on toolbar with that of selected request.

We're leaning towards a panel with selectable request as it reuses same UI and requires the least amount of changes.

Ideas, feedback on this topic would be appreciated!

**Comment by kagux** [comment]
closed by #54
