### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by OvermindDL1** [kagux/ex_debug_toolbar#51]
Followed the instructions to add it to my application and I get this error on load:

```elixir
** (Mix) Could not start application ex_debug_toolbar: ExDebugToolbar.Application.start(:normal, []) returned an error: shutdown: failed to start child: ExDebugToolbar.Breakpoint.ServerNode
```

There should probably be a bit of logging whenever something fails to load about why it failed to load.  :-)

**Comment by OvermindDL1** [comment]
And indeed, running `ExDebugToolbar.Breakpoint.ServerNode.start_link()` returns `:error`.

**Comment by OvermindDL1** [comment]
And Tracing into it shows that for some reason (wtf?!) `start_link/0` is trying to run `Node.start` (seen at https://github.com/kagux/ex_debug_toolbar/blob/master/lib/ex_debug_toolbar/breakpoint/server_node.ex#L9), which is returning:
```elixir
{:error,
 {{:already_started, #PID<0.46.0>},
  {:child, :undefined, :net_sup_dynamic,
   {:erl_distribution, :start_link,
    [[:breakpoint_host@myservername, :longnames, 15000], false]}, :permanent, 1000,
   :supervisor, [:erl_distribution]}}}
```
In addition (as seen on https://github.com/kagux/ex_debug_toolbar/blob/master/lib/ex_debug_toolbar/breakpoint/server_node.ex#L11 calling https://github.com/kagux/ex_debug_toolbar/blob/master/lib/ex_debug_toolbar/breakpoint/server_node.ex#L32) it is trying to change the secret of the Node to a *HIGHLY* insecure secret of (WTF?!?) `:secret`, which of course would break my server anyway since then it would not be able to talk with the other Nodes that run other services as it would not be able to talk to them.

So first, wtf overriding distribution, no library should be controlling or even touching that, at all!

Second, why the heck is it trying to open distribution on the computer open *name* (wtf?!) thus allowing external connections to insecurely connect to this node (*never* do that!).

Third, why the heck is it trying to set it to an insecure key (while also opening it up to its full name, thus allowing any random person on the network (or in my case the internet since it is exposed) to take complete and entire control of this machine trivially (would not actually work in my case since I have epmd's port externally blocked except for over tunnels thankfully).

Do *not* touch Distribution setup from a library, *ever*, even at dev time!

**Comment by kagux** [comment]
the distribution is needed to connect external iex session with Phoenix server. I agree, there's a lot of room for improvement on how to handle it:
* it should respect existing distribution 
* name and secret should be dynamic 

Ideas, suggestions and PRs in this area are most welcome.

**Comment by OvermindDL1** [comment]
First of all, move the cookie and nodename both to the config file instead of hard coding.  ^.^
Though honestly I'd dynamically generate those (and do not use the servername as the `@` part, instead use `String.to_atom("#{nodename}@127.0.0.1")` explicitly if distribution was not already running, and generate the secret via a crypto random generation or something only if distribution is not already running).

Second, make it not crash if distribution is already going.  :-)

Third, you can get the nodename and cookie by querying `Node` if they are already set, should use those if they already exist (the config options should not override the existing values if distribution is already enabled).

As it is right now though, anyone using this library can have their BEAM VM pretty trivially crashed at best to wiping their system at worst (or more? as they have full access to the BEAM open).  ^.^;

Distribution is not something to mess with lightly.  :-)

Though, I've not looked, but what is stopping you from just starting a new process inside the current BEAM VM instead of slaving out to a secondary node?

**Comment by kagux** [comment]
Dynamic values should prevent crashing. 

Ideally, if there was a way to start iex session in a new process, that would simplify everything. I don't know if that's possible though and how to pass user input to it.

**Comment by OvermindDL1** [comment]
> Ideally, if there was a way to start iex session in a new process, that would simplify everything. I don't know if that's possible though and how to pass user input to it.

Oh definitely can do so, you just launch a process of it while redirecting it's inputs/outputs.  Why would that need to be done?  If you can point me to the lines of code where you run commands on iex I might be able to get you real system commands to do the same things instead?  Like `pry` is just a wrapper around tracing as I recall as one example.  :-)

**Comment by kagux** [comment]
Thing is, its not only about executing specific iex commands, its about providing a complete shell experience. 

The only command we run explicitly is pry:
https://github.com/kagux/ex_debug_toolbar/blob/master/lib/ex_debug_toolbar/breakpoint/client_node.ex#L12

**Comment by OvermindDL1** [comment]
Is the shell only brought up when something is 'break'd on or all the time?

**Comment by kagux** [comment]
the shell is created when user clicks on a breakpoint from toolbar.

**Comment by OvermindDL1** [comment]
Quick question, what if multiple pages are open with people debugging in each simultaneously, do they use the same external node or each spawn one (if each spawn one you could run out of system resources really fast).

Well in general, starting an IEx shell in the same node is as simple as just running `IEx.start()` (potentially with options).

In general, if IEx is already loaded then this is set, but if not (and it is safe to call this in 'most cases' regardless):
```elixir
      :application.set_env(:stdlib, :shell_prompt_func,
                           {IEx.CLI, :prompt})
```
That sets the prompt to, well, nothing since Elixir renders its own.
You can start up a new IEx evaluator process by running `IEx.start()` with any options if you want.  You will need to change the `Process.group_leader/2` so you can redirect it's output, then just send messages through that mock group leader back and forth as you need.

Honestly though, I'd just make my own 'shell' for debugging in, you can evaluate lines of code passed in to it easily, plus you could tightly control exactly what is done then because as it is this is pretty open to everyone.  ^.^;

As an aside, it would be nice to have a way to turn the toolbar on/off depending on factors in the app (like if a certain user is logged in for example), which can be done by a simple plug if you give us an interface for turning it on/off for a single request?  :-)

**Comment by kagux** [comment]
Hey,
It took me a while to get back to this issue, as it's pretty big.
I have a question to you, why do you want to control 'shell' and enable/disable per user in your development environment? I'd like to understand your use case better.

**Comment by kagux** [comment]
Alright, I made a stub at running IEx right in the same application.

My understanding of how it could work:
 1. Join breakpoint channel
 2. Create IO device to mediate input/output
 3. Start IEx if not running
 4. Change group leader for IEx to our IO device
 5. Revert group leader once done

I faced a bunch of problems:
* if server is started with iex shell, then I don't understand how to change group leader. IEx servere is started in `spawn` and `Server.whois` returns something different.
* if iex is not running, `IEx.start()` is not enough, `IEx.Pry.pry` doesn't recognize it as running. I've tried `:user.start()`, but that raises errors.

So, for now I've removed distribution from current implementation, which is a step forward. And now we can take our time to figure out running IEx from application if it's possible.

**Comment by kagux** [comment]
I'll close this for now, but feel free to reopen if you want to continue this discussion

**Comment by OvermindDL1** [comment]
> I have a question to you, why do you want to control 'shell' and enable/disable per user in your development environment? I'd like to understand your use case better.

I don't, that would be for 'your' use, you could choose whatever shell you want running via whatever communication pipes you want without needing to run another process (thus opening the development system up to attacks by force enabling epmd distribution in it and/or breaking development node communication since the cookie is changed when it should not be).  :-)

> if server is started with iex shell, then I don't understand how to change group leader. IEx servere is started in spawn and Server.whois returns something different.

You change the group leader by specifying it via a few ways, but via rpc:call is the easiest, you can see how (in erlang at least) at:  https://gist.github.com/mentels/6bd4c970cabb818b0d4c

> if iex is not running, IEx.start() is not enough, IEx.Pry.pry doesn't recognize it as running. I've tried :user.start(), but that raises errors.

Correct, you'll have to rebuild the hooks within it while registring the proper processes (such as the group leader).

> So, for now I've removed distribution from current implementation, which is a step forward. And now we can take our time to figure out running IEx from application if it's possible.

It is possible, just a big pain.  ^.^;

Removing the need for distribution is hugely useful though, it removes the attack vector and would allow it to work in apps that already connect over the mesh in other ways.  :-)

**Comment by kagux** [comment]
thanks @OvermindDL1, you've been very helpful with this issue! I don't think we'll have enough time to tackle group leader approach in the near future. But once we get around to it, we'd love to get your feedback.

**Comment by OvermindDL1** [comment]
> But once we get around to it, we'd love to get your feedback.

My free time pops in and out (mostly out lately, very busy at work) but ping me whenever looking at it and I'll help as I can.  :-)
