### ISSUE TITLE
Toolbar Doesn't Display

### ISSUE THREAD

**Issue by dikaio** [kagux/ex_debug_toolbar#72]
There's a conflict in the use of Bootstrap 4 and the ex_debug_toolbar using Bootstrap 3. I couldn't find the exact conflict but it is in the CSS and not the javascript.

**Comment by kagux** [comment]
@dikaio, how do you include bootstrap 4 in your project?

**Comment by dikaio** [comment]
Hi @kagux! I currently import via sass. Here's my configuration:

**brunch-config.js**
```js
exports.config = {
  files: {
    javascripts: {
      joinTo: "js/app.js",
      order: {
        before: [
          "vendor/js/jquery.min.js",
          "vendor/js/popper.min.js",
          "vendor/js/jquery.smartWizard.min.js",
          "vendor/js/flickity.pkgd.min.js",
          "vendor/js/scrollMonitor.js",
          "vendor/js/smooth-scroll.polyfills.js",
          "vendor/js/prism.js",
          "vendor/js/zoom.min.js",
          "vendor/js/sweetalert2.js",
          "vendor/js/bootstrap.js",
          "vendor/js/theme.js"
        ]
      }
    },
    stylesheets: {
      joinTo: "css/app.css",
      order: {
        after: ["css/app.scss"]
      }
    },
    templates: {
      joinTo: "js/app.js"
    }
  },
  conventions: {
    assets: /^(static)/
  },
  paths: {
    watched: ["static", "css", "js", "vendor", "scss", "fonts"],
    public: "../priv/static"
  },
  plugins: {
    babel: {
      ignore: [/vendor/]
    },
    sass: {
      mode: 'native'
    }
  },
  modules: {
    autoRequire: {
      "js/app.js": ["js/app"]
    }
  },
  npm: {
    enabled: true
  }
};
```

**app.scss**

```scss
$icon-font-path: "/fonts/";
@import "wingman/socicon";
@import "wingman/entypo";
@import "wingman/theme";
@import "wingman/custom";
```

The `theme.scss` file is where bootstrap resides, it's just a modification of bootstrap 4 variables. [Here's theme.scss](https://gist.github.com/dikaio/ab23341768a677e53b42435374fa58db). I did consider that this was a conflict between the theme and bootstrap 3 so I downloaded a fresh copy of bootstrap 4 and replaced the theme.scss and was still unable to get **ex_debug_toolbar to work**. Here's a screenshot of what I'm seeing.

<img width="1120" alt="screenshot 2018-03-14 12 27 34" src="https://user-images.githubusercontent.com/869535/37426275-28b5ab0a-2783-11e8-9c64-e80eaada9f2c.png">

The toolbar is there and I can see the data in the source it's just not expanding and there's no errors in the browser console.

**Comment by kagux** [comment]
thanks!
I'll have a look at it in coming days

**Comment by kagux** [comment]
Hi @dikaio,

Could you please try `fix/bootstrap-4-css` branch? 

`{:ex_debug_toolbar, github: "kagux/ex_debug_toolbar", branch: "fix/bootstrap-4-css"}`

**Comment by dikaio** [comment]
Hi @kagux - I tried getting it going but got the following error messages:

```elixir
=> ex_debug_toolbar
Compiling 53 files (.ex)
warning: unused alias Encoder
  lib/ex_debug_toolbar/poison/encoder.ex:12

warning: conflicting behaviours found. function init/1 is required by Plug and Plug (in module ExDebugToolbar.Plug.RequestId)
  lib/ex_debug_toolbar/plug/request_id.ex:1

warning: conflicting behaviours found. function call/2 is required by Plug and Plug (in module ExDebugToolbar.Plug.RequestId)
  lib/ex_debug_toolbar/plug/request_id.ex:1

warning: function init/1 required by behaviour GenServer is not implemented (in module ExDebugToolbar.Database.RequestRepo).

We will inject a default implementation for now:

    def init(args) do
      {:ok, args}
    end

But you want to define your own implementation that converts the arguments given to GenServer.start_link/3 to the server state

  lib/ex_debug_toolbar/database/request_repo.ex:1

warning: this clause cannot match because a previous clause at line 117 always matches
  lib/ex_debug_toolbar.ex:1
```

I wasn't sure if these new errors had something to do with old package so I wiped it `rm -rf deps _build; mix do deps.get, deps.compile` and still have the same errors.

It's very possible this is just an issue with my setup so I will come back around to this in the next couple days and see what I come up with.

**Comment by kagux** [comment]
Hi @dikaio, 

I got similar warning on elixir 1.6.4. Was testing it against 1.6.2. 
Updated PR, warnings should be fixed. Note, these were not errors, so the app and toolbar should have been working. Was it not the case?

**Comment by dikaio** [comment]
Hi @kagux. I can confirm that the update was working before I disabled but I will try to get it all back up over the weekend.

Thanks so much for making this bootstrap 4 ready so quickly 👍

**Comment by kagux** [comment]
thanks! closing the issue
